AWSTemplateFormatVersion: 2010-09-09
Description: Basic EC2 Instance
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0fb653ca2d3203ac1  
      InstanceType: t2.micro
      KeyName: cfn-key-2
      SecurityGroups:
        - default
        - !Ref  SSHSecurityGroup
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Port SSH allowed
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22' 
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080' 
          CidrIp: 0.0.0.0/0
  EC2EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref  Ec2Instance.
      
          
          


