AWSTemplateFormatVersion: 2010-09-09
Description: Basic EC2 Instance
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0fb653ca2d3203ac1  
      InstanceType: t2.micro
      KeyName: cfn-key-2
      SecurityGroups:
        - default

